### ISSUE TITLE
SDK demands imports that aren't part of the spec

### ISSUE THREAD

**Issue by Spoonbender** [proxy-wasm/proxy-wasm-rust-sdk#104]
I'm trying to create a plugin using proxy-wasm-rust-sdk which will run inside a [proxy-wasm-go-host](https://github.com/mosn/proxy-wasm-go-host).
My plugin fails to initialize due to missing imports (not provided by the Go host).
These missing imports are not a part of the ABI spec as it appears [here](https://github.com/proxy-wasm/spec/blob/56ef3547de853d4d989a5b866f510d3ae713d8d4/abi-versions/vNEXT/README.md)
They include the following functions:
- `proxy_clear_route_cache`
- `proxy_continue_request`
- `proxy_continue_response`
- `proxy_get_configuration`
- `proxy_send_local_response`

I understand these functions are a part of Envoy specifically, but not a part of the ABI.

I propose that any such function which isn't part of the ABI will be excludable using the Rust conditional compilation feature, e.g. by having an `envoy` feature (to opt-in all envoy-specific functions) or a `abi-x.y.z` feature (to opt-out any function which doesn't comply with this ABI version).

(If accepted and some implementation guidelines are provided, then I can issue a PR)

**Comment by PiotrSikora** [comment]
Thanks for the report!

I agree that any Envoy specific ABI extensions should be guarded by a feature. However, that's not what's happening here. Those functions are in fact part of the ABI v0.1.0, which Rust SDK implements (update to ABI v0.2.1 is pending merge in https://github.com/proxy-wasm/proxy-wasm-rust-sdk/pull/64).

Proxy-Wasm Go Host claims support for ABI v0.1.0 and v0.2.0, but it doesn't implement either correctly (see: https://github.com/mosn/proxy-wasm-go-host/issues/10).

Note that [the vNEXT in proxy-wasm/spec repo](https://github.com/proxy-wasm/spec/tree/master/abi-versions/vNEXT) is a work-in-progress for the next iteration of the specification (hence vNEXT), and there is no documentation for either ABI v0.1.0, v0.2.0 or v0.2.1, so Envoy and SDKs are effectively the specification for those versions.
