### ISSUE TITLE
set_http_response_body() doesn't work in http callout reply

### ISSUE THREAD

**Issue by dandlake** [proxy-wasm/proxy-wasm-rust-sdk#116]
Hi,

I see there is an example of set_http_response_body() in examples/http_body.rs. I tried this and it works. However, if I move the same set_http_response_body() call into a http callout reply, I got error code 2(BadArgument).

```
[2021-06-05 23:28:35.975][3741][trace][wasm] [source/extensions/common/wasm/wasm_vm.cc:39] [vm<-host] env.proxy_log return: 0
[2021-06-05 23:28:35.975][3741][trace][wasm] [source/extensions/common/wasm/wasm_vm.cc:39] [vm->host] env.proxy_set_buffer_bytes(1, 0, 17, 1245960, 16)
[2021-06-05 23:28:35.975][3741][trace][wasm] [source/extensions/common/wasm/wasm_vm.cc:39] [vm<-host] env.proxy_set_buffer_bytes return: 2
```

Is this supposed to work? If I want to track it down to see why BadArgument is returned, since there is no more detail in the trace, what function in envoy code can I set a breaekpoint on?

Thanks,

**Comment by jcrugzz** [comment]
@dandlake my experience with BadArgument is coming from making the http_call in the filter without providing an authority. If you have a code example I could see what I can tell.

**Comment by dandlake** [comment]
@jcrugzz Thank you for your reply. Below is my sample code, which is a combination of the example http_auth_random.rs and http_body.rs.

`
use log::trace;
use proxy_wasm::traits::*;
use proxy_wasm::types::*;
use std::time::Duration;

#[no_mangle]
pub fn _start() {
    proxy_wasm::set_log_level(LogLevel::Trace);
    proxy_wasm::set_http_context(|_, _| -> Box<dyn HttpContext> { Box::new(HttpAuthRandom) });
}

struct HttpAuthRandom;

impl HttpContext for HttpAuthRandom {
    fn on_http_response_headers(&mut self, _: usize) -> Action {
        self.set_http_response_header("content-length", None);
        Action::Continue
    }

    fn on_http_response_body(&mut self, body_size: usize, end_of_stream: bool) -> Action {
        if !end_of_stream {
            // Wait -- we'll be called again when the complete body is buffered
            // at the host side.
            return Action::Pause;
        }

        /*   if I modify response body here, it works.
        let new_body = format!("Original message body ({} bytes) redacted.", body_size);
        self.set_http_response_body(0, body_size, &new_body.into_bytes());
        Action::Continue
        */
        self.dispatch_http_call(
            "httpbin",
            vec![
                (":method", "GET"),
                (":path", "/bytes/1"),
                (":authority", "httpbin.org"),
            ],
            None,
            vec![],
            Duration::from_secs(5),
        )
        .unwrap();
        Action::Pause
    }
}

impl Context for HttpAuthRandom {
    fn on_http_call_response(&mut self, _: u32, _: usize, body_size: usize, _: usize) {
        let new_body = format!("Original message body ({} bytes) redacted.", body_size);
        self.set_http_response_body(0, body_size, &new_body.into_bytes());

        trace!("access granted.");
        self.resume_http_response();
    }
}
`

With this code, I got the BadArgument for the set_http_response_body() call in on_http_call_response(). If the set_http_response_body() call is moved to inside on_http_response_body(), as it is in the example http_body.rs, it works.

The error in the log looks like:
`

[2021-07-18 04:19:40.191][413541][trace][http] [source/common/http/async_client_impl.cc:121] async http request response data (length=0 end_stream=true)
[2021-07-18 04:19:40.191][413541][trace][wasm] [source/extensions/common/wasm/wasm_vm.cc:39] [host->vm] proxy_on_http_call_response(1, 1, 9, 1, 0)
[2021-07-18 04:19:40.192][413541][trace][wasm] [source/extensions/common/wasm/wasm_vm.cc:39] [vm->host] env.proxy_set_effective_context(2)
[2021-07-18 04:19:40.192][413541][trace][wasm] [source/extensions/common/wasm/wasm_vm.cc:39] [vm<-host] env.proxy_set_effective_context return: 0
[2021-07-18 04:19:40.192][413541][trace][wasm] [source/extensions/common/wasm/wasm_vm.cc:39] [vm->host] env.proxy_set_buffer_bytes(1, 0, 1, 1114248, 41)
[2021-07-18 04:19:40.192][413541][trace][wasm] [source/extensions/common/wasm/wasm_vm.cc:39] [vm<-host] env.proxy_set_buffer_bytes return: 2
[2021-07-18 04:19:40.192][413541][trace][wasm] [source/extensions/common/wasm/wasm_vm.cc:39] [vm->host] env.proxy_log(5, 1114440, 136)
[2021-07-18 04:19:40.192][413541][critical][wasm] [source/extensions/common/wasm/context.cc:1232] wasm log test test: panicked at 'unexpected status: 2', /home/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/proxy-wasm-0.1.4/src/hostcalls.rs:149:23
`
I hope I can debug into set_http_response_body() to find out why BadArgument is returned.

**Comment by dandlake** [comment]
Some update. After sync to latest main to pick up https://github.com/envoyproxy/envoy/pull/17280, I don't get BadArgument anymore. However, the buffer replacement is not quite right. The new string shows up at the beginning of the response body, but the original page shows up after it too. Looks like a string insertion(at the beginning) happened, instead of a replacement.  @PiotrSikora, @mathetake  Can you help take a look? Is this a bug?

 ```
< HTTP/1.1 200 OK
< server: envoy
< date: Wed, 21 Jul 2021 22:44:52 GMT
< content-type: text/html
< last-modified: Mon, 30 Sep 2019 02:46:31 GMT
< etag: "5d916c87-4f3"
< x-frame-options: SAMEORIGIN
< accept-ranges: bytes
< x-envoy-upstream-service-time: 4
< transfer-encoding: chunked
< 
Original message body (1 bytes) redacted.!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
...  the rest of the nginx default page 
```

In the good case, response body was replaced properly:

```
< HTTP/1.1 200 OK
< server: envoy
< date: Wed, 21 Jul 2021 22:40:10 GMT
< content-type: text/html
< last-modified: Mon, 30 Sep 2019 02:46:31 GMT
< etag: "5d916c87-4f3"
< x-frame-options: SAMEORIGIN
< accept-ranges: bytes
< x-envoy-upstream-service-time: 5
< transfer-encoding: chunked
< 
* Connection #0 to host 127.0.0.1 left intact
Original message body (1267 bytes) redacted.
```

**Comment by PiotrSikora** [comment]
The `body_size` in `on_http_call_response` refers to the body size of the HTTP callout response, so you're replacing only as many bytes (possibly none) as you received in the HTTP callout response body.

I believe that if you change your code from:
```
self.set_http_response_body(0, body_size, &new_body.into_bytes());
```
to:
```
self.set_http_response_body(0, 0xffffffff, &new_body.into_bytes());
```
then it should work.

**Comment by dandlake** [comment]
Thanks for the help, @PiotrSikora! Yes, this works now. So, your fix in envoyproxy/envoy#17280 worked. And it was my mistake to only replace 1 byte(httpbin reply size) in my test above. After replacing that 1 with 0xffffffff, as you suggested, the whole response body was replaced properly.

**Comment by PiotrSikora** [comment]
@dandlake replacing complete body using `0xffffffff` always worked, envoyproxy/envoy#17280 added support for partial replacements/drains, which "unblocked you" because you were previously using the unsupported length to replace.

**Comment by dandlake** [comment]
I see. Thanks for the explanation.
