### ISSUE TITLE
Multiple definition of `_start' when running unit tests

### ISSUE THREAD

**Issue by aweis89** [proxy-wasm/proxy-wasm-rust-sdk#119]
Hey,
When running unit tests with `cargo test`, I get a linking error complaining about multiple definitions of `_start`: `src/lib.rs:15: multiple definition of _start';`
When changing the name of that function, unit tests work as expected but the WASM binary no longer gets initialized properly within the Envoy VM.
Notably, only when testing against the target `x86_64-apple-darwin`, there's no linking error. But using any other linux or WASM target seems to produce the above issue.

Any suggestions for how mitigate this would be much appreciated!

**Comment by lavignes** [comment]
You could add a `#[cfg(not(test))]` attribute to your `_start` function.
Or alternatively add something like `#[cfg(target_arch = "wasm32")]`:

```
#[cfg(not(test))]
#[no_mangle]
pub fn _start() {
    // ...
}
```
