### ISSUE TITLE
New Release for Proxy-Wasm ABI v0.2.1

### ISSUE THREAD

**Issue by captiosus** [proxy-wasm/proxy-wasm-rust-sdk#128]
Hi,

Is there a timeline for a new release to catch https://github.com/proxy-wasm/proxy-wasm-rust-sdk/pull/64?

**Comment by Swaagie** [comment]
Would it be possible to setup a Github Action release workflow that also published the crate to crates.io? Could be exclusively run if the commit message contains `release` for example.

**Comment by PiotrSikora** [comment]
> Is there a timeline for a new release to catch #64?

Sorry for the delay, I'll try to get the next release out in next 2 weeks, as there are some bugs that I want to fix first.

> Would it be helpful to setup a Github Action release workflow that also published the crate to crates.io? Could be exclusively run if the commit message contains `release` for example.
> 
> edit: mostly considering semantic release actions for Rust aren't quite there yet from what I've been able to find.

Tagged releases are pushed via `cargo publish` from a clean checkout. While I'm not against using GitHub Actions, I'm not sure I understand what problem are you're trying to solve.

**Comment by Swaagie** [comment]
> as there are some bugs that I want to fix first.

Are there specific issues for each of these bugs the community can help solve? 

> Tagged releases are pushed via cargo publish from a clean checkout. While I'm not against using GitHub Actions, I'm not sure I understand what problem are you're trying to solve.

True, not specifically a tech problem. Simply a suggestion to make for easy process.

**Comment by cortex93** [comment]
Any progress for this release ?

**Comment by PiotrSikora** [comment]
I've added all the remaining PRs and issues to the [v0.2.0](https://github.com/proxy-wasm/proxy-wasm-rust-sdk/milestone/1) milestone, and the release should be published later this week.

**Comment by PiotrSikora** [comment]
All key PRs are merged, so this is ready to go. I'll make a release on Friday, in case anybody wants to tests it before then.
