### ISSUE TITLE
Runnable examples

### ISSUE THREAD

**Issue by Swaagie** [proxy-wasm/proxy-wasm-rust-sdk#140]
This is more a discussion than an issue. Would it be valuable to move every example into it's own folder and include a matching envoy config + docker compose config? This should allow developers exploring the proxy-wasm SDK to run the example easily.

If this is considered valuable, I can contribute the changes.

**Comment by PiotrSikora** [comment]
Yes, I've been meaning to do this for a while (and I have some examples that are not committed because of that).

Please make sure all examples are still built as part of the CI (I believe that moving them to subdirectories will prevent `cargo` from building them).
