### ISSUE TITLE
`hostcalls::open_grpc_stream` does not register closed streams, upstream failures result in panic

### ISSUE THREAD

**Issue by Protryon** [proxy-wasm/proxy-wasm-rust-sdk#153]
At the moment:
* `hostcalls::open_grpc_stream` only registers stream IDs when connections are successful
* Envoy calls close_grpc_stream on the stream id that is passed in, even when the original `open_grpc_stream` failed.
* `close_grpc_stream` can't route to the proper context and panics on `invalid token_id`

This seems to be an issue of ambiguous specification. I will open a PR to fix this, but it may be considered that Envoy is in the wrong here instead. Either way, we probably shouldn't panic.

Update:
* Envoy doesn't return the token ID, but still fires the on_close event. We will just need to ignore/log in on_grpc_close.

**Comment by fmcato** [comment]
We might be hit by this when using unary grpc calls (seems to be triggered by invalid calls due to bad GRPC upstream configuration).

Let me know if I can help here.
