### ISSUE TITLE
How to get user remote IP address?

### ISSUE THREAD

**Issue by beckend** [proxy-wasm/proxy-wasm-rust-sdk#158]
Having hard time to find it in the docs.

**Comment by ismailbaskin** [comment]
If you use [use_remote_address: true](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#:~:text=the%20connection%20manager.-,use_remote_address,-(BoolValue)%20If) on `envoy.filters.network.http_connection_manager` filter you can access remote IP address with `x-forwarded-for` header.

**Comment by beckend** [comment]
Thanks
