### ISSUE TITLE
grpc callout unusual behavior

### ISSUE THREAD

**Issue by GOVYANSONG** [proxy-wasm/proxy-wasm-rust-sdk#163]
I am trying to do a grpc callout from on_http_request_body to a local grpc service. The dispatch_grpc_call returned no error but the request did not seem to reach the grpc service. I had run health check and mock request to the same service from cli tools, can verify that the service works as expected. I am not sure where the issue is.

Code snippets attached herebelow:

on_http_request_body:

println!("grpc server : {} , message length : {}", self.cluster, vbuf.len() );

        match self.dispatch_grpc_call(
            &self.cluster,
            "logistics.AuthService",
            "Allow",
            Vec::<(&str, &[u8])>::new(),
            Some(vbuf.as_slice()),
            Duration::from_secs(5),
        ) {
            Ok(_) => println!("invocation success"),
            Err(e) => println!("invocation failure {:?}", e),
        }

        Action::Pause

envoy.yaml:

clusters:
- name: opa_grpc
      connect_timeout: 2s
      type: STATIC
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: opa_grpc
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1
                      port_value: 8085

**Comment by GOVYANSONG** [comment]
Here is logging from envoy admin, all requests have failed:

opa_grpc::observability_name::opa_grpc
opa_grpc::default_priority::max_connections::1024
opa_grpc::default_priority::max_pending_requests::1024
opa_grpc::default_priority::max_requests::1024
opa_grpc::default_priority::max_retries::3
opa_grpc::high_priority::max_connections::1024
opa_grpc::high_priority::max_pending_requests::1024
opa_grpc::high_priority::max_requests::1024
opa_grpc::high_priority::max_retries::3
opa_grpc::added_via_api::false
opa_grpc::127.0.0.1:8085::cx_active::1
opa_grpc::127.0.0.1:8085::cx_connect_fail::0
opa_grpc::127.0.0.1:8085::cx_total::1
opa_grpc::127.0.0.1:8085::rq_active::0
opa_grpc::127.0.0.1:8085::rq_error::4
opa_grpc::127.0.0.1:8085::rq_success::0
opa_grpc::127.0.0.1:8085::rq_timeout::0
opa_grpc::127.0.0.1:8085::rq_total::4
opa_grpc::127.0.0.1:8085::hostname::
opa_grpc::127.0.0.1:8085::health_flags::healthy
opa_grpc::127.0.0.1:8085::weight::1
opa_grpc::127.0.0.1:8085::region::
opa_grpc::127.0.0.1:8085::zone::
opa_grpc::127.0.0.1:8085::sub_zone::
opa_grpc::127.0.0.1:8085::canary::false
opa_grpc::127.0.0.1:8085::priority::0
opa_grpc::127.0.0.1:8085::success_rate::-1
opa_grpc::127.0.0.1:8085::local_origin_success_rate::-1

**Comment by GOVYANSONG** [comment]
here is output from stats, note upstream_rq_400 and upstream_rq_4xx:

cluster.opa_grpc.assignment_stale: 0
cluster.opa_grpc.assignment_timeout_received: 0
cluster.opa_grpc.bind_errors: 0
cluster.opa_grpc.circuit_breakers.default.cx_open: 0
cluster.opa_grpc.circuit_breakers.default.cx_pool_open: 0
cluster.opa_grpc.circuit_breakers.default.rq_open: 0
cluster.opa_grpc.circuit_breakers.default.rq_pending_open: 0
cluster.opa_grpc.circuit_breakers.default.rq_retry_open: 0
cluster.opa_grpc.circuit_breakers.high.cx_open: 0
cluster.opa_grpc.circuit_breakers.high.cx_pool_open: 0
cluster.opa_grpc.circuit_breakers.high.rq_open: 0
cluster.opa_grpc.circuit_breakers.high.rq_pending_open: 0
cluster.opa_grpc.circuit_breakers.high.rq_retry_open: 0
cluster.opa_grpc.default.total_match_count: 1
cluster.opa_grpc.http1.dropped_headers_with_underscores: 0
cluster.opa_grpc.http1.metadata_not_supported_error: 0
cluster.opa_grpc.http1.requests_rejected_with_underscores_in_headers: 0
cluster.opa_grpc.http1.response_flood: 0
cluster.opa_grpc.internal.upstream_rq_400: 5
cluster.opa_grpc.internal.upstream_rq_4xx: 5
cluster.opa_grpc.internal.upstream_rq_completed: 5
cluster.opa_grpc.lb_healthy_panic: 0
cluster.opa_grpc.lb_local_cluster_not_ok: 0
cluster.opa_grpc.lb_recalculate_zone_structures: 0
cluster.opa_grpc.lb_subsets_active: 0
cluster.opa_grpc.lb_subsets_created: 0
cluster.opa_grpc.lb_subsets_fallback: 0
cluster.opa_grpc.lb_subsets_fallback_panic: 0
cluster.opa_grpc.lb_subsets_removed: 0
cluster.opa_grpc.lb_subsets_selected: 0
cluster.opa_grpc.lb_zone_cluster_too_small: 0
cluster.opa_grpc.lb_zone_no_capacity_left: 0
cluster.opa_grpc.lb_zone_number_differs: 0
cluster.opa_grpc.lb_zone_routing_all_directly: 0
cluster.opa_grpc.lb_zone_routing_cross_zone: 0
cluster.opa_grpc.lb_zone_routing_sampled: 0
cluster.opa_grpc.max_host_weight: 0
cluster.opa_grpc.membership_change: 1
cluster.opa_grpc.membership_degraded: 0
cluster.opa_grpc.membership_excluded: 0
cluster.opa_grpc.membership_healthy: 1
cluster.opa_grpc.membership_total: 1
cluster.opa_grpc.original_dst_host_invalid: 0
cluster.opa_grpc.retry_or_shadow_abandoned: 0
cluster.opa_grpc.update_attempt: 0
cluster.opa_grpc.update_empty: 0
cluster.opa_grpc.update_failure: 0
cluster.opa_grpc.update_no_rebuild: 0
cluster.opa_grpc.update_success: 0
cluster.opa_grpc.upstream_cx_active: 1
cluster.opa_grpc.upstream_cx_close_notify: 0
cluster.opa_grpc.upstream_cx_connect_attempts_exceeded: 0
cluster.opa_grpc.upstream_cx_connect_fail: 0
cluster.opa_grpc.upstream_cx_connect_timeout: 0
cluster.opa_grpc.upstream_cx_connect_with_0_rtt: 0
cluster.opa_grpc.upstream_cx_destroy: 0
cluster.opa_grpc.upstream_cx_destroy_local: 0
cluster.opa_grpc.upstream_cx_destroy_local_with_active_rq: 0
cluster.opa_grpc.upstream_cx_destroy_remote: 0
cluster.opa_grpc.upstream_cx_destroy_remote_with_active_rq: 0
cluster.opa_grpc.upstream_cx_destroy_with_active_rq: 0
cluster.opa_grpc.upstream_cx_http1_total: 1
cluster.opa_grpc.upstream_cx_http2_total: 0
cluster.opa_grpc.upstream_cx_http3_total: 0
cluster.opa_grpc.upstream_cx_idle_timeout: 0
cluster.opa_grpc.upstream_cx_max_duration_reached: 0
cluster.opa_grpc.upstream_cx_max_requests: 0
cluster.opa_grpc.upstream_cx_none_healthy: 0
cluster.opa_grpc.upstream_cx_overflow: 0
cluster.opa_grpc.upstream_cx_pool_overflow: 0
cluster.opa_grpc.upstream_cx_protocol_error: 0
cluster.opa_grpc.upstream_cx_rx_bytes_buffered: 84
cluster.opa_grpc.upstream_cx_rx_bytes_total: 420
cluster.opa_grpc.upstream_cx_total: 1
cluster.opa_grpc.upstream_cx_tx_bytes_buffered: 0
cluster.opa_grpc.upstream_cx_tx_bytes_total: 1500
cluster.opa_grpc.upstream_flow_control_backed_up_total: 0
cluster.opa_grpc.upstream_flow_control_drained_total: 0
cluster.opa_grpc.upstream_flow_control_paused_reading_total: 0
cluster.opa_grpc.upstream_flow_control_resumed_reading_total: 0
cluster.opa_grpc.upstream_http3_broken: 0
cluster.opa_grpc.upstream_internal_redirect_failed_total: 0
cluster.opa_grpc.upstream_internal_redirect_succeeded_total: 0
cluster.opa_grpc.upstream_rq_0rtt: 0
cluster.opa_grpc.upstream_rq_400: 5
cluster.opa_grpc.upstream_rq_4xx: 5
cluster.opa_grpc.upstream_rq_active: 0
cluster.opa_grpc.upstream_rq_cancelled: 0
cluster.opa_grpc.upstream_rq_completed: 5
cluster.opa_grpc.upstream_rq_maintenance_mode: 0
cluster.opa_grpc.upstream_rq_max_duration_reached: 0
cluster.opa_grpc.upstream_rq_pending_active: 0
cluster.opa_grpc.upstream_rq_pending_failure_eject: 0
cluster.opa_grpc.upstream_rq_pending_overflow: 0
cluster.opa_grpc.upstream_rq_pending_total: 1
cluster.opa_grpc.upstream_rq_per_try_idle_timeout: 0
cluster.opa_grpc.upstream_rq_per_try_timeout: 0
cluster.opa_grpc.upstream_rq_retry: 0
cluster.opa_grpc.upstream_rq_retry_backoff_exponential: 0
cluster.opa_grpc.upstream_rq_retry_backoff_ratelimited: 0
cluster.opa_grpc.upstream_rq_retry_limit_exceeded: 0
cluster.opa_grpc.upstream_rq_retry_overflow: 0
cluster.opa_grpc.upstream_rq_retry_success: 0
cluster.opa_grpc.upstream_rq_rx_reset: 0
cluster.opa_grpc.upstream_rq_timeout: 0
cluster.opa_grpc.upstream_rq_total: 5
cluster.opa_grpc.upstream_rq_tx_reset: 0
cluster.opa_grpc.version: 0

**Comment by GOVYANSONG** [comment]
cluster.opa_grpc.upstream_cx_http1_total / cluster.opa_grpc.upstream_cx_http2_total, i am wondering if grpc callout in sdk sends http1.1 instead of 2.0 for native grpc call. the service listens on both native grpc and grpc-web. the http1.1 request could be treated as grpc-web which is definitely not expected. I will debug this one.

**Comment by PiotrSikora** [comment]
It doesn't look that `opa_grpc` is configured as HTTP/2 upstream, you need to add:
```
    typed_extension_protocol_options:
      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
        "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
        explicit_http_config:
          http2_protocol_options: {}
```

**Comment by GOVYANSONG** [comment]
PiotrSkiora's comment above resolved the issue: set HTTP/2 for native grpc.

**Comment by GOVYANSONG** [comment]
Just a follow up question: the grpc call indeed occurred successfully. the grpc service log showed response and there is no error anywhere. but on_grpc_call_response did not seem to get called because no printout was displayed in console:

impl Context for MyHttp{
    fn on_grpc_call_response(&mut self, token_id: u32, status_code: u32, response_size: usize) {
        println!("token_id : {}", token_id.to_string());
        println!("status_code : {}", status_code.to_string());
        println!("response_size : {}", response_size.to_string());
        self.resume_http_request()
    }
}

any insight would be appreciated

**Comment by GOVYANSONG** [comment]
More info: if i stop the grpc upstream service, i can see following logs:

wasm log: token_id : 25
wasm log: status_code : 14
wasm log: response_size : 0

**Comment by GOVYANSONG** [comment]
if i move the grpc callout logic from on_http_request_body to on_http_request_headers, the on_grpc_response handler was correctly called. @PiotrSikora is it true that grpc callout cannot be made in on_http_request_body method?

**Comment by GOVYANSONG** [comment]
switched to cpp version and build with envoy codebase. working example functions as expected.
