### ISSUE TITLE
Getting proxy_on_grpc_close error when attempting to use WasmPlugin in istio

### ISSUE THREAD

**Issue by collinlee** [proxy-wasm/proxy-wasm-rust-sdk#189]
When attempting to use Istio WasmPlugin for a wasm plugin that makes GRPC calls (github.com:NomadXD/envoy-wasm-rust-grpc.git)) in my service mesh.

I am seeing this error in the istio ingressgateway logs:

│ 2023-02-24T21:40:36.044290Z    error    envoy wasm    Function: proxy_on_grpc_close failed: Uncaught RuntimeError: unreachable 
│ Proxy-Wasm plugin in-VM backtrace:     
│   0:  0x9c71c - rust_panic                            
│   1:  0x1bb51 - _ZN3std9panicking20rust_panic_with_hook17h911ba172265603dfE       
│   2:  0x1afcd - _ZN3std9panicking11begin_panic28_$u7b$$u7b$closure$u7d$$u7d$17h4a44d4e36300edadE                                                 │   3:  0x18fb9 - _ZN3std10sys_common9backtrace26__rust_end_short_backtrace17h4a844d9a68816ef5E                                                |   4:  0x9f61 - _ZN3std9panicking11begin_panic17hc74be07c1db66ccdE                                                                               
│   5:  0x939a - _ZN83_$LT$envoy_wasm_rust_grpc..ExampleFilter$u20$as$u20$proxy_wasm..traits..Context$GT$21on_grpc_call_response17h67f3abf900b3e33 
│   6:  0x9b52e - proxy_on_grpc_close
│   7:  0xa1982 - proxy_on_grpc_close.command_export 

The docker-compose example provided that uses envoy doesn't give the same error.
I'm trying to understand if this is an issue with Istio or Envoy.

istioctl version
client version: 1.12.8
control plane version: 1.12.8
data plane version: 1.12.8 (2 proxies)

Has anyone else come across this before?

**Comment by collinlee** [comment]
I think is actually caused by calling the panic function in the rust code.

**Comment by PiotrSikora** [comment]
@collinlee you're probably hitting #153, fixed in #154. You need upgrade to `proxy-wasm = "0.2"`.

**Comment by collinlee** [comment]
Thanks @PiotrSikora.  A bit unrelated question, but I can't seem to figure out what the service parameter in the function dispatch_grpc_call really means.  In the example from https://github.com/NomadXD/envoy-wasm-rust-grpc it's "api.ExampleService" (from the protoc results in rust that point to the proto file for the service).  However, is this equivalent to an actual service name in kubernetes outside of this example?  The envoy-wasm-rust-grpc's example works great out of the box - but that is assuming the usage of the docker compose environment.  I can't seem to get the equivalent working porting this to istio and loading the generated rust wasm with WasmPlugin.  I always get GRPC status 14 even after having defined a cluster name for the go grpc service.   Is there more documentation on dispatch_grpc_call I could find somewhere?

**Comment by PiotrSikora** [comment]
> A bit unrelated question, but I can't seem to figure out what the service parameter in the function dispatch_grpc_call really means. In the example from https://github.com/NomadXD/envoy-wasm-rust-grpc it's "api.ExampleService" (from the protoc results in rust that point to the proto file for the service). However, is this equivalent to an actual service name in kubernetes outside of this example? The envoy-wasm-rust-grpc's example works great out of the box - but that is assuming the usage of the docker compose environment. I can't seem to get the equivalent working porting this to istio and loading the generated rust wasm with WasmPlugin. I always get GRPC status 14 even after having defined a cluster name for the go grpc service. Is there more documentation on dispatch_grpc_call I could find somewhere?

From that example:
- `"grpc_service"` is the name of the upstream/cluster/k8s service that you're trying to reach,
- `"api.ExampleService"` is the `service` name from the gRPC proto definition,
- `"GenerateHeader"` is the RPC method from the gRPC proto definition.

You might need to add the upstream name via Istio's `EnvoyFilter` patching `CLUSTER`.

**Comment by collin-lee** [comment]
I have something like this:

`apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: wasm-filter
  namespace: istio-system
spec:
  workloadSelector:
    # select by label in the same namespace
    labels:
      istio: ingressgateway
  configPatches:
    # The Envoy config you want to modify
    - applyTo: CLUSTER
      match:
        cluster:
          service: "grpc-go"
      patch:
        operation: ADD
        value:
          name: grpc_cluster
          type: STRICT_DNS
          connect_timeout: 10s
          lb_policy: ROUND_ROBIN
          http2_protocol_options: {}
          load_assignment:
            cluster_name: grpc_cluster
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: "grpc-go.default.svc.cluster.local"
                          port_value: 50051`

And then the wasm is loaded via WasmPlugin like this:

`apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: wasm-plugin
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  phase: STATS
  pluginName: add_header
  url: oci://docker.io/joekahuna/cors-wasm:http_headers
  imagePullPolicy: Always`

**Comment by PiotrSikora** [comment]
I don't see the code, but from the errors it sounds like you might be mixing request and response maps (e.g. trying to set request headers in the response path).

**Comment by collinlee** [comment]
It's the code from here: [https://github.com/NomadXD/envoy-wasm-rust-grpc/blob/main/filter/src/lib.rs#L76-#L91](here).  I tried commenting out the line ```self.resume_http_request```  but the issue remains.   Will try using other callbacks
