### ISSUE TITLE
 http_auth_random.rs example does not work

### ISSUE THREAD

**Issue by dgn** [proxy-wasm/proxy-wasm-rust-sdk#19]
The example compiles fine, but when it attempts to call httpbin.org, it stacktraces on the `.unwrap()` call:

```
[Envoy (Epoch 0)] [2020-08-04 11:08:22.059][42][critical][wasm] [external/envoy/source/extensions/common/wasm/context.cc:1098] wasm log custom-filter custom-filter_root: panicked at 'called `Result::unwrap()` on an `Err` value: BadArgument', examples/http_auth_random.rs:30:9
```

I tried both creating a `httpbin` ServiceEntry and a Service, neither work. If I'm holding this wrong, this will at least need some documentation on how it can be used.

Testing with Istio 1.5.4

**Comment by PiotrSikora** [comment]
Could you try using `outbound|8000||httpbin.default.svc.cluster.local`? Istio mangles names.

**Comment by dgn** [comment]
Thanks, that did the trick- I had copied the cluster name from `istioctl pc cluster`'s output, and it was different for some reason

**Comment by PiotrSikora** [comment]
Great!

btw: we have to drop support for Istio 1.5.x (see #5 for details). I'm going to release `v0.1.1` that will still work with it, but we've messed up the ABI and using Proxy-Wasm is going to require Istio 1.6.x or newer going forward (this is true for all SDKs).

**Comment by dgn** [comment]
> Great!
> 
> btw: we have to drop support for Istio 1.5.x (see #5 for details). I'm going to release `v0.1.1` that will still work with it, but we've messed up the ABI and using Proxy-Wasm is going to require Istio 1.6.x or newer going forward (this is true for all SDKs).

Thanks for the heads-up! Not an issue for me, I was planning to release this for 1.6 anyway. Does this mean the current ABI does not work with 1.6? What's the schedule for the breaking version update?

**Comment by PiotrSikora** [comment]
Already broken, but the change was minimal (see: #5, #7).

For the reference:
[v0.1.0] and [v0.1.1] work with Istio 1.5,
[v0.1.2] and future releases work with Istio 1.6, Istio 1.7 and Envoy-Wasm (master).

[v0.1.0]: https://github.com/proxy-wasm/proxy-wasm-rust-sdk/releases/tag/v0.1.0
[v0.1.1]: https://github.com/proxy-wasm/proxy-wasm-rust-sdk/releases/tag/v0.1.1
[v0.1.2]: https://github.com/proxy-wasm/proxy-wasm-rust-sdk/releases/tag/v0.1.2
