### ISSUE TITLE
dispatch_http_call support http2?

### ISSUE THREAD

**Issue by LugiaChang** [proxy-wasm/proxy-wasm-rust-sdk#194]
How can I use http2 to send msg by dispatch_http_call?

**Comment by PiotrSikora** [comment]
You need to configure your proxy to use HTTP/2 when connecting to the next hop.

**Comment by LugiaChang** [comment]
> You need to configure your proxy to use HTTP/2 when connecting to the next hop.

Thank you. In istio, I set the port name to http2, which automatically switched to http/2.
