### ISSUE TITLE
Health check

### ISSUE THREAD

**Issue by antonengelhardt** [proxy-wasm/proxy-wasm-rust-sdk#220]
Hey,

Is there any way to find out if the envoy has started the plugin and finished the configuration? It would be nice for liveness and readiness checks in Kubernetes.

Cheers.

**Comment by PiotrSikora** [comment]
It's more likely that you'll get answer to that question in the Envoy issue tracker than here, since it doesn't sound like this is specific to the Rust SDK.

cc @kyessenov for some ideas

**Comment by kyessenov** [comment]
I think it's the same as any other filter in Envoy. Check for a listener to start listener at startup, or listener to get warmed for reloaded.
