### ISSUE TITLE
Update to fix build in rust nightly

### ISSUE THREAD

**Issue by martijneken** [proxy-wasm/proxy-wasm-rust-sdk#227]
Can we publish a new SDK version?
More generalized question: can we set up a regular publishing cadence?

Reason: proxy-wasm v0.2.1 depends on ahash v0.8.3, which depends on stdsimd, which is now gone:
https://users.rust-lang.org/t/error-e0635-unknown-feature-stdsimd/106445

This means ProxyWasm is broken in Rust nightly builds, which are required for features like local benchmarking (`#![feature(test)]`).

```
$ cargo +nightly build
error[E0635]: unknown feature `stdsimd`
  --> ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ahash-0.8.3/src/lib.rs:99:42
   |
99 | #![cfg_attr(feature = "stdsimd", feature(stdsimd))]
   |                                          ^^^^^^^
```

```
$ cargo tree -i ahash 
ahash v0.8.3
└── hashbrown v0.13.2
    └── proxy-wasm v0.2.1
```

Workaround:
```
$ rustup install nightly-2024-01-01
$ cargo +nightly-2024-01-01 build
```

**Comment by martijneken** [comment]
Oof never mind, I ran `rm Cargo.lock` and it builds fine against ahash 0.8.11.

**Comment by antonengelhardt** [comment]
@martijneken `cargo update` does the same btw

**Comment by martijneken** [comment]
@antonengelhardt I appreciate the tip, thank you!
