### ISSUE TITLE
Updating query params

### ISSUE THREAD

**Issue by akshayxml** [proxy-wasm/proxy-wasm-rust-sdk#238]
Is it possible to change the query param of the request? Couldn't find any function which could be used for that.

**Comment by martijneken** [comment]
Hi there, yes it's possible. For Envoy at least, the Wasm module will receive the query as part of the `:path` pseudo header. Here is a sample Rust plugin to parse the path using the url crate: https://github.com/GoogleCloudPlatform/service-extensions-samples/blob/main/plugins/samples/query_log/plugin.rs

Mutating it would just require updating the :path header.
