### ISSUE TITLE
bug  use open_grpc_stream create health stream  and send failed grpc server panic

### ISSUE THREAD

**Issue by pi-pi-miao** [proxy-wasm/proxy-wasm-rust-sdk#260]
use grpc stream  code  potential risks  panic

example:
match self.open_grpc_stream(
            request.get_redis_addr(),
            "package.name",
            "MetricStream",
            vec![],
        ) {
            Err(e) => {
                error!("open grpc err {:?}",e);
                false
            }
            Ok(status) => {
                //  grpc server is health
                //  sudden the grpc server is crash  or other thing
                self.send_grpc_stream_message(status, Some(&msg), true);  // here will panic ,because grpc server is crash
                true
            }
        }

**Comment by PiotrSikora** [comment]
Could you post stacktrace? Does the plugin panic or does the host crash?

**Comment by pi-pi-miao** [comment]
> Could you post stacktrace? Does the plugin panic or does the host crash?

"Any connection drop would cause a crash due to the underlying error handling using unwrap. I have fixed this issue and resolved numerous crash problems. The fix can be reviewed and merged in the pull request at https://github.com/proxy-wasm/proxy-wasm-rust-sdk/pull/264."
