### ISSUE TITLE
Rust SDK is missing metrics API 

### ISSUE THREAD

**Issue by yskopets** [proxy-wasm/proxy-wasm-rust-sdk#4]

**Comment by czh-123-rust** [comment]
* hello @PiotrSikora , when I use metric's interface to test prometheus function, I found that the return value of get_metric() is alway 0. And prometheus can not receive the metric counter data normally. The code is shown below.

lazy_static! {
    static ref SCP_REQ_METRIC_ID: Mutex<u32> = 
        Mutex::new(define_metric(MetricType::Counter, "http_request").unwrap());
}
pub fn get_metric_id() -> u32 {
    let scp_req_metric_id = SCP_REQ_METRIC_ID.lock().unwrap();
    *scp_req_metric_id
}

impl HttpContext for Limiter {
    fn on_http_request_headers(&mut self, _: usize) -> Action {
        info!("=====on_http_request_headers=====");
        if let Some(_val) = self.get_http_request_header("metrics") {
            increment_metric(get_metric_id(), 1).unwrap();
            info!("---new metric_id={:?}", get_metric_id());
            let get_return_value = get_metric(get_metric_id()).unwrap();
            info!("---get_return_value={:?}", get_return_value);
        }
......
......

* Out put information:  
wasm log rate-limit.default rate_limit_handle: =====on_http_request_headers=====  
wasm log rate-limit.default rate_limit_handle: ---new metric_id=4  
wasm log rate-limit.default rate_limit_handle: ---get metric ok, return_value=0  
wasm log rate-limit.default rate_limit_handle: ---get_return_value=0
