### ISSUE TITLE
upstream connect error or disconnect/reset before headers. reset reason: local reset

### ISSUE THREAD

**Issue by charlesvhe** [proxy-wasm/proxy-wasm-rust-sdk#57]
Hi, I follow "Extending Istio with Rust and WebAssembly"
https://blog.red-badger.com/extending-istio-with-rust-and-webassembly

after "wasme deploy envoy ...", filter can receive  request console log:
`[2020-11-27 06:26:45.306][32][info][wasm] [external/envoy/source/extensions/common/wasm/context.cc:1152] wasm log: Got 16 HTTP headers in #2.`

but curl retrun error:
```
curl http://localhost:8080/headers
upstream connect error or disconnect/reset before headers. reset reason: local reset
```

I'm use windows 10 docker-desktop WSL2 backend, and build source code in WLS2 Ubuntu.
full command list:
```
cargo build --target wasm32-unknown-unknown --release
cp target/wasm32-unknown-unknown/release/envoy_filter.wasm ./
wasme build precompiled envoy_filter.wasm --tag envoy_filter:v0.1
wasme list
wasme deploy envoy envoy_filter:v0.1 -e istio/proxyv2:1.8.0
```

source code:
[envoy-filter.zip](https://github.com/proxy-wasm/proxy-wasm-rust-sdk/files/5606389/envoy-filter.zip)

Could you help me how to fix this issue : )

**Comment by PiotrSikora** [comment]
The filter looks fine, although you should verify that `authority` is set before setting `x-hello` header - perhaps set the header value inside the loop instead of storing it and setting afterwards?

In any case, this doesn't look like an issue with the Rust SDK. Is the upstream configured correctly in Envoy? Does it work fine without the filter?

**Comment by charlesvhe** [comment]
It's not rust SDK issue, the document in README is out of date, not work with istio 1.8：

"Extending Istio with Rust and WebAssembly"
https://blog.red-badger.com/extending-istio-with-rust-and-webassembly

I have follow envoy's example and works fine: https://github.com/envoyproxy/envoy/tree/master/examples/wasm-cc
