### ISSUE TITLE
Unlike in other SDKs, there is no link between `RootContext` and `HttpContext` / `StreamContext`

### ISSUE THREAD

**Issue by yskopets** [proxy-wasm/proxy-wasm-rust-sdk#6]
## Summary

* Due to a missing link between `RootContext` and `HttpContext`, it's not possible to to apply to `HttpContext` configuration that was set in the `RootContext` during `proxy_on_configure`
* Why is `HttpContext` gets created by a standalone factory function rather than by `RootContext` ?

**Comment by mileswilson** [comment]
I'm also trying to understand how to solve this problem, and pass configuration to my HttpContext.

**Comment by dgn** [comment]
I just wasted a bunch of time on this. If the callbacks would accept closures with environment captures, this wouldn't be an issue

**Comment by bangau1** [comment]
I am also trying to reading configuration and pass it into `HttpContext`, but can't do that. 
I notice that this article https://docs.eupraxia.io/docs/how-to-guides/deploy-rust-based-envoy-filter/ use forked version which basically let the `RootContext` create the `HttpContext` (so can inject the configuration to them). For now, I am using the article approach (the forked version)
