### ISSUE TITLE
Cannot send blocking external requests from on_http_request_body

### ISSUE THREAD

**Issue by robertpanzer** [proxy-wasm/proxy-wasm-rust-sdk#66]
While it is possible to execute a blocking external request from on_http_request_headers(), this doesn't seem to work when initiated from on_http_request_body.

Expected behavior:
When a filter returns Action::Pause on all executions of `on_http_response_body()` and successfully dispatches an external request, then the request should not be forwarded to the configured cluster before `on_http_call_response()` is called which invokes `resume_http_request()`.

Observed behavior:
Even though invoking `dispatch_http_call()` in `on_http_response_body()` returns a success, the request is immediately forwarded to the configured cluster and the response is immediately returned.
The response to the dispatched call does not arrive at the filter.

I created a reproducer project at https://github.com/robertpanzer/rust-wasm-examples that has all necessary steps to reproduce in the readme.

**Comment by PiotrSikora** [comment]
Repeating what I wrote in https://github.com/robertpanzer/rust-wasm-examples/pull/1#issuecomment-747102055:
> @robertpanzer Your code works fine, the issue is that the test backend (i.e. Envoy's `direct_response`) returns response without waiting for the request body, so it's not great for testing this particular behavior. Using a real backend solves the issue (I like to use `httpbin.org` for that purpose).

**Comment by robertpanzer** [comment]
Hi @PiotrSikora,

But the reproducer uses an external server, ie one that is not the same Envoy process. 
Is it just because it's localhost?

**Comment by PiotrSikora** [comment]
The issue is not with the auth server (that works fine), but with the fake backend (`"staticreply"`).

**Comment by robertpanzer** [comment]
Ah ok, now I see it, the "standard" route was pointing to the static response listener.
It works indeed if I also point that to a "real" backend.
