### ISSUE TITLE
gRPC support

### ISSUE THREAD

**Issue by gxb5443** [proxy-wasm/proxy-wasm-rust-sdk#90]
Hey is there any plan to implement gRPC calls?

**Comment by PiotrSikora** [comment]
Yes, once https://github.com/envoyproxy/envoy/pull/15208 is merged, since right now this feature is blocked on protobuf.

So, hopefully, in a next few weeks.

**Comment by codefromthecrypt** [comment]
I'll add a pre-emptive concern suggestion, which is to make sure (enforce) it is optional, as each dependency slows and adds heft to the compilation process. Not saying folks aren't thinking about this, but compilation time is a big issue for projects who have CI downstream.

**Comment by PiotrSikora** [comment]
@gxb5443 fixed in #100, #101, and #107. I'll spin 0.1.4 release that includes them in the next few days.

@codefromthecrypt there are no new dependencies.

**Comment by PiotrSikora** [comment]
@dosten released in v0.1.4, sorry for the delay.
