### ISSUE TITLE
Random numbers

### ISSUE THREAD

**Issue by sonhal** [proxy-wasm/proxy-wasm-rust-sdk#97]
I am building a module that needs random numbers, preferably CSPRNG. Is there a good way of getting a hold of this?

**Comment by PiotrSikora** [comment]
Use `getrandom` crate, see example:
https://github.com/proxy-wasm/proxy-wasm-rust-sdk/blob/1534ef2386ed0da62dd42e5352d4b1a2177764df/examples/hello_world.rs#L51

**Comment by sonhal** [comment]
Do I then need use the wasm32-wasi target? with `cargo build --target wasm32-unknown-unknown --release` I get:  `error[E0425]: cannot find function getrandom in this scope`

Cargo.toml:
```
[package]
name = "authn-filter"
version = "0.1.0"
authors = ["Sondre"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/filter.rs"
crate-type = ["cdylib"]

[dependencies]
log = "0.4.14"
proxy-wasm = "0.1.3" # The Rust SDK for proxy-wasm
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
url = "2.2.1"
oauth2 = { version = "3.0",  default-features = false }
base64 = "0.13.0"

[target.'cfg(not(all(target_arch = "wasm32", target_os = "unknown")))'.dependencies]
getrandom = "0.2"
```

**Comment by sonhal** [comment]
Thank you, that worked great! Is there any docs you can point to regarding WASI support in Envoy?
